
/etc/courier/faxcoverpage.tr
/etc/courier/faxnotifyrc
/etc/courier/faxrc
/usr/lib/courier/faxmail/application-pdf.filter
/usr/lib/courier/faxmail/application-postscript.filter
/usr/lib/courier/faxmail/coverpage
/usr/lib/courier/faxmail/image-gif.filter
/usr/lib/courier/faxmail/image-jpeg.filter
/usr/lib/courier/faxmail/image-png.filter
/usr/lib/courier/faxmail/init
/usr/lib/courier/faxmail/new_fax
/usr/lib/courier/faxmail/text-plain.filter
/usr/share/courier/webadmin/admin-34fax.html
/usr/share/courier/webadmin/admin-34fax.pl
/usr/share/courier/webadmin/admin-35fax.html
/usr/share/courier/webadmin/admin-35fax.pl
/usr/share/man/man8/courierfax.8
