'\" t
.\"<!-- Copyright 1999 - 2011 Double Precision, Inc.  See COPYING for -->
.\"<!-- distribution information. -->
.\"     Title: testmxlookup
.\"    Author: Sam Varshavchik
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/24/2017
.\"    Manual: Double Precision, Inc.
.\"    Source: Courier Mail Server
.\"  Language: English
.\"
.TH "TESTMXLOOKUP" "1" "07/24/2017" "Courier Mail Server" "Double Precision, Inc."
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
testmxlookup \- Look up mail relays for a domain
.SH "SYNOPSIS"
.HP \w'\fBtestmxlookup\fR\ 'u
\fBtestmxlookup\fR [@\fIip\-address\fR] [\-\-dnssec] [\-\-udpsize\ \fIn\fR] {\fIdomain\fR}
.SH "DESCRIPTION"
.PP
\fBtestmxlookup\fR
lists the names and IP addresses of mail relays that receive mail for the
\fIdomain\fR\&. This is useful in diagnosing mail delivery problems\&.
.PP
\fBtestmxlookup\fR
sends a DNS MX query for the specified domain, followed by A/AAAA queries, if needed\&.
\fBtestmxlookup\fR
lists the hostname and the IP address of every mail relay, and its MX priority\&.
.SS "DIAGNOSTICS"
.PP
The error message "Hard error" indicates that the domain does not exist, or does not have any mail relays\&. The error message "Soft error" indicates a temporary error condition (usually a network failure of some sorts, or the local DNS server is down)\&.
.SS "OPTIONS"
.PP
@ip\-address
.RS 4
Specify the DNS server\*(Aqs IP address, where to send the DNS query to, overriding the default DNS server addresses read from
/etc/resolv\&.conf\&.
.sp
\(lqip\-address\(rq
must be a literal, numeric, IP address\&.
.RE
.PP
\-\-dnssec
.RS 4
Enable the
DNSSEC
extension\&. If the DNS server has
DNSSEC
enabled, and the specified domain\*(Aqs DNS records are signed, the list of IP addresses is suffixed by
\(lq(DNSSEC)\(rq, indicating a signed response\&.
.sp
This is a diagnostic option\&. Older DNS servers may respond with an error, to a DNSSEC query\&.
.RE
.PP
\-\-udpsize \fIn\fR
.RS 4
Specify that
\fIn\fR
is the largest
UDP
packet size that the DNS server may send\&. This option is only valid together with
\(lq\-\-dnssec\(rq\&. If
\(lq\-\-dnssec\(rq
always returns an error, try
\(lq\-\-udpsize 512\(rq
(the default setting is 1280 bytes, which is adequate for Ethernet, but other kinds of networks may impose lower limits)\&.
.RE
.SH "SEE ALSO"
.PP
\m[blue]\fB\fBcourier\fR(8)\fR\m[]\&\s-2\u[1]\d\s+2,
\m[blue]\fBRFC 1035\fR\m[]\&\s-2\u[2]\d\s+2\&.
.SH "AUTHOR"
.PP
\fBSam Varshavchik\fR
.RS 4
Author
.RE
.SH "NOTES"
.IP " 1." 4
\fBcourier\fR(8)
.RS 4
\%http://www.courier-mta.org/courier.html
.RE
.IP " 2." 4
RFC 1035
.RS 4
\%http://www.rfc-editor.org/rfc/rfc1035.txt
.RE
